name: Daily Stock Analysis

on:
  # Manual trigger
  workflow_dispatch:
  
  # Scheduled trigger: Run daily at 4:30 PM IST (11:00 AM UTC)
  schedule:
    - cron: '15 9 * * *'  # Runs at 9:15 AM IST

jobs:
  analyze-stocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
          
      - name: Build
        run: go build -o go-stock
        
      - name: Run Stock Analysis
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: ./go-stock